language: generic

before_install:
   - curl -L https://sourceforge.net/projects/zsh/files/latest/download > zsh.tar.xz
   - tar -xv --xz -f zsh.tar.xz
   - cd zsh*/
   - ./configure --prefix="${HOME}/.local"
   - make
   - make install
   - cd -
   - rm -fr zsh*

env:
  - SHELL=sh
  - SHELL=bash
  - SHELL="zsh -y"

install:
  - PATH="$HOME/.local/bin:$PATH"

script:
  - make "TEST_SHELL=${SHELL}" tests

after_failure:
  - make "TEST_SHELL=${SHELL} -x" tests

